package connect4.player;

/**
 * @author yang
 * User select
 */
public enum PlayerBMode {
    // PVP
    Human,
    /**
     * PVC
     * Computer's decision is generated by
     * `Random.nextInt()`
     */
    RNG,
    /**
     * TODO
     * Not started yet
     * Generate by algorithm
     *
     * a little bit smart
     */
    MiniMax,
}
